# Generated by Django 3.1.7 on 2021-03-18 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensagem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='nome',
            field=models.CharField(default='anonimo', max_length=100),
        ),
    ]
